# Generated by Django 6.0.5 on 2026-05-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
